import {
  Bot,
  CheckCircle2,
  AlertCircle,
} from "lucide-react";

import type { Citation } from "../../types/chat";

import { CitationCard } from "./CitationCard";

interface AssistantMessageProps {
  content: string;
  citations: Citation[];
  grounded: boolean;
  model?: string;
}

export function AssistantMessage({
  content,
  citations,
  grounded,
  model,
}: AssistantMessageProps) {
  return (
    <div className="message-row assistant-row">
      <div className="assistant-avatar">
        <Bot size={19} />
      </div>

      <div className="assistant-message-wrapper">
        <div className="message assistant-message">
          <div className="answer-text">
            {content}
          </div>

          <div
            className={
              grounded
                ? "grounded-indicator grounded"
                : "grounded-indicator not-grounded"
            }
          >
            {grounded ? (
              <CheckCircle2 size={14} />
            ) : (
              <AlertCircle size={14} />
            )}

            {grounded
              ? "Grounded in retrieved documents"
              : "Unable to verify grounding"}
          </div>

          {model && (
            <div className="model-label">
              Generated by {model}
            </div>
          )}
        </div>

        {citations.length > 0 && (
          <div className="citations-section">
            <h4>Sources</h4>

            <div className="citation-list">
              {citations.map((citation) => (
                <CitationCard
                  key={citation.citation_id}
                  citation={citation}
                />
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}